package net.tebyan.filesharingapp.classes;

public class WebserviceUrl {
    public static String NewName = "&newName=";
    public static String LastName = "&lastName=";
    public static String UserName = "&userName=";
    public static String Number = "&number=";
    public static String FriendId = "&friendIds=";
    public static String FileId = "&fileid=";
    public static String ps = "&ps=";
    public static String FolderId = "&folderId=";
    public static String SiteUrl = "http://file.tebyan.net:81";
    public static String SiteUrlHTTPS = "https://file.tebyan.net:81";
    public static String RepositoryServiceUrl = SiteUrl + "/api/Repository/";
    public static String AccountServiceUrl = SiteUrl + "/api/Account/";
    public static String UploadServiceUrl = RepositoryServiceUrl + "Upload";
    public static String SendLoginCode = AccountServiceUrl + "SendLoginCode?number=";
    public static String GetTokenByVCode = AccountServiceUrl + "GetTokenByVCode?number=";
    public static String GetAccountInfo = AccountServiceUrl + "GetAccountInfo";
    public static String NewFolderRequest = RepositoryServiceUrl + "NewFolder?name=";
    public static String GetFiles = RepositoryServiceUrl + "GetFiles?mode=Drive&folder=";
    public static String GetDeletedFiles = RepositoryServiceUrl + "GetFiles?mode=Trash&folderId=";
    public static String GetSharedFilesWithMe = RepositoryServiceUrl + "GetFiles?mode=ShareMe&folderId=";
    public static String GetStaredFiles = RepositoryServiceUrl + "GetFiles?mode=Stars&folder=";
    public static String staredFiles = RepositoryServiceUrl + "Star";
    public static String DeleteFile = RepositoryServiceUrl + "Trash";
    public static String RestoreFile = RepositoryServiceUrl + "Restore";
    public static String RenameFile = RepositoryServiceUrl + "Rename?id=";
    public static String CopyFile = RepositoryServiceUrl + "Copy?id=";
    public static String MoveFile = RepositoryServiceUrl + "Move?id=";
    public static String Delete = RepositoryServiceUrl + "Delete";
    public static String UnStar = RepositoryServiceUrl + "UnStar";
    public static String ZipFile = RepositoryServiceUrl + "ZipFile";
    public static String UnZipFile = RepositoryServiceUrl + "UnZipFile";
    public static String GetFileInfo = RepositoryServiceUrl + "GetFileInfo?fileId=";
    public static String GetFriends = SiteUrl + "/api/Account/GetFriends";
    public static String AddFriends = SiteUrl + "/api/Account/AddFriend";
    public static String AddFriend = SiteUrl + "/api/Account/AddFriend?firstName=";
    public static String FullShareFile = SiteUrl + "/api/Repository/" + "FullShareFile";
    public static String GetFriendsForShareFile = SiteUrl + "/api/Account/GetFriendsForShareFile?fileId=";
    public static String SearchFile = RepositoryServiceUrl + "GetFiles?mode=SearchFile&folder=";
    public static String BuyStorage = SiteUrl + "/Common/BuySpace";
    public static String DownloadFile = SiteUrl + "/Open/Token_";
    public static String FileIdDownload = "/Download/";
    public static String RemoveAvatar = SiteUrl + "/api/Account/RemoveAvatar";
    public static String UpdateProfile = SiteUrl + "/api/Account/UpdateProfile?firstName=";
    public static String UpdateAvater = SiteUrl + "/api/Account/UpdateAvatar";
    public static String RegisterDevice = SiteUrl + "/api/Account/RegisterDevice?deviceId=";
    public static String GetTokenByDevice = SiteUrl + "/api/Account/GetTokenByDevice?deviceId=";
}